dom 30 abr 2023 21:34:13 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/void-install b/void-install
--- a/void-install
+++ b/void-install
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-#shellcheck disable=SC2145,SC2001,SC2188,SC2015,SC2155,SC2317,SC2320,SC2291,SC2034,SC2016,SC2154,SC2207,SC2166,SC2128,SC2059,SC2140,SC2031,SC2030,SC2036
+#shellcheck disable=SC2145,SC2001,SC2188,SC2015,SC2155,SC2317,SC2320,SC2291,SC2034,SC2120,SC2086,SC2319
+#shellcheck disable=SC2016,SC2154,SC2207,SC2166,SC2128,SC2059,SC2140,SC2031,SC2030,SC2036,SC2119,SC2027
 
 #  void-install
 #  Created: 2022/12/24
@@ -38,7 +39,7 @@ shopt -s extglob
 
 #system
 readonly APP="${0##*/}"
-readonly _VERSION_='1.6.509-20230430'
+readonly _VERSION_='1.6.515-20230430'
 readonly	distro=$(uname -n)
 readonly DEPENDENCIES=(dialog awk tar sed cat grep sort tr chroot blkid fdisk parted lsblk curl xz mkfs.vfat tee lvm cryptsetup)
 #                      cfdisk gdisk sfdisk efivar mkfs.ext2 mkfs.ext3 mkfs.ext4 mkfs.btrfs mkfs.xfs mkfs.f2fs mkfs.jfs mkfs.reiserfs)
@@ -50,7 +51,7 @@ readonly _TARBALL_ROOTFS=void-x86_64-base-custom-current.tar.xz
 #
 declare -i quiet=0 grafico=0 ncounter=0
 declare -i LAUTO=1 LINSTALL=0 LCHROOT=0 LBIND=0 LMKPART=0 LEFI=0 LBIOS=1 LMKPARTED=0 LOSPROBER=0 LFDE=0 LVM=0
-declare -gA AsUser=([cuser]= [cfullname]= [cpass]='void' [cpassroot]='voidlinux' [chostname]='voidlinux' [cgroups]='wheel,audio,video,floppy,cdrom,optical,kvm,xbuilder')
+declare -gA AsUser=([cpass]='void' [cpassroot]='voidlinux' [chostname]='voidlinux' [cgroups]='wheel,audio,video,floppy,cdrom,optical,kvm,xbuilder')
 declare -gA Amntpoint
 declare -gA AmntpointFDE
 declare -gA Amkfs
@@ -355,14 +356,15 @@ sh_checkDependencies() {
 			echo
 			if readconf "${yellow}${cmsg_InstCommand[$LC_DEFAULT]} '${cyan}${missing[*]}${reset}' ?"; then
 				if xbps-install -Sy "${missing[@]}"; then
+					errorFound=0
 					sh_checkDependencies
-					#die "${cmsg_RunNew[$LC_DEFAULT]}"
 				else
 					die "${cmsg_RunNewErro[$LC_DEFAULT]}"
 				fi
 			fi
+		else
+			die "${cmsg_ERRO[$LC_DEFAULT]}: ${cmsg_InstalacaoAbortada[$LC_DEFAULT]}..."
 		fi
-		die "${cmsg_ERRO[$LC_DEFAULT]}: ${cmsg_InstalacaoAbortada[$LC_DEFAULT]}..."
 	fi
 }
 
@@ -385,23 +387,13 @@ sh_setVarColors() {
 		purple=$(tput setaf 125);
 		violet=$(tput setaf 61);
 	else
-		sh_unetVarColors
+		sh_unsetVarColors
 	fi
 }
 
 sh_unsetVarColors() {
-	reset=''
-	green=''
-	red=''
-	bold=''
-	blue=''
-	cyan=''
-	orange=''
-	pink=''
-	white=''
-	yellow=''
-	#violet=''
-	#purple=''
+	unset reset green red bold blue cyan
+	unset orange pink white yellow violet purple
 	sh_setLogPrefix
 }
 
@@ -409,8 +401,8 @@ sh_setLogPrefix() {
 	COL_NC='\e[0m' # No Color
 	COL_LIGHT_GREEN='\e[1;32m'
    COL_LIGHT_RED='\e[1;31m'
-	TICK="$white[${COL_LIGHT_GREEN}✓${COL_NC}${white}]"
-	CROSS="$white[${COL_LIGHT_RED}✗${COL_NC}$white]"
+	TICK="${white}[${COL_LIGHT_GREEN}✓${COL_NC}${white}]"
+	CROSS="${white}[${COL_LIGHT_RED}✗${COL_NC}$white]"
 	INFO="[i]"
 	# shellcheck disable=SC2034
 	DONE="${COL_LIGHT_GREEN} done!${COL_NC}"
@@ -1312,7 +1304,7 @@ sh_mount_fs() {
 				mkdir -p "$dir_install${mntpoint}"
 				last_msg="${cmsg_MontandoParticao[$LC_DEFAULT]} ${_part} ($dir_install) ${cmsg_Em[$LC_DEFAULT]} $dir_install${mntpoint}"
 				msg "INFO" "$last_msg" "$(log_info_msg "$last_msg")"
-				mount ${_part} "$dir_install${mntpoint}"
+				mount "${_part}" "$dir_install${mntpoint}"
 				evaluate_retval "$?"
 				break
 			fi
@@ -1332,7 +1324,7 @@ sh_mount_fs() {
 			mkdir -p "$dir_install${mntpoint}"
 			last_msg="${cmsg_MontandoParticao[$LC_DEFAULT]} ${_part} ($dir_install) ${cmsg_Em[$LC_DEFAULT]} $dir_install${mntpoint}"
 			msg "INFO" "$last_msg" "$(log_info_msg "$last_msg")"
-			mount ${_part} "$dir_install${mntpoint}"
+			mount "${_part}" "$dir_install${mntpoint}"
 			evaluate_retval "$?"
 		done
 	fi
@@ -1761,7 +1753,7 @@ sh_chooseTimezone() {
 	local area
 
 	for area in "${areas[@]}"; do
-		read -r -a locations -d '\n' < <(find /usr/share/zoneinfo/$area -type f -printf '%P\n')
+		read -r -a locations -d '\n' < <(find /usr/share/zoneinfo/"$area" -type f -printf '%P\n')
 		for key in "${locations[@]}"; do
 			Atimezone+=([$key]="$area/$key")
 		done
@@ -2118,17 +2110,14 @@ $(printf "%${nlen}s$sep%-4s$sep%-6s$sep%6s$sep%-6s$sep%-15s$sep%-30s" "DEVICE" "
          ;;
 		esac
 
-
-#	      AARRAY_DSK_DEVICES+=(["$PATH_"]="$NAME_|$SIZE_|${TRAN_:-${TYPE_}}|${MODEL_:-unknown}|${LABEL_:-""}|${SERIAL_:-""}|${PTTYPE_:-""}|${FSTYPE_:-"none"}|${PARTTYPENAME_:-none}")
-
     	if [[ -n "$sd" ]]; then
 			_DEVICE="$sd"
 			AConfDisk[_DEVICE]="$sd"
     		index=$(sh_seekstrarray "${ARRAY_DSK_DEVICES[*]}" "$_DEVICE")
-			NAME_ORIGEM="$(sh_splitarray "${AARRAY_DSK_DEVICES[$_DEVICE]}" $DSK_NAME)"
-			MODEL_ORIGEM="$(sh_splitarray "${AARRAY_DSK_DEVICES[$_DEVICE]}" $DSK_MODEL)"
-			SIZE_ORIGEM="$(sh_splitarray "${AARRAY_DSK_DEVICES[$_DEVICE]}" $DSK_SIZE)"
-			TRAN_ORIGEM="$(sh_splitarray "${AARRAY_DSK_DEVICES[$_DEVICE]}" $DSK_TRAN)"
+			NAME_ORIGEM="$(sh_splitarray "${AARRAY_DSK_DEVICES[$_DEVICE]}" "$DSK_NAME")"
+			MODEL_ORIGEM="$(sh_splitarray "${AARRAY_DSK_DEVICES[$_DEVICE]}" "$DSK_MODEL")"
+			SIZE_ORIGEM="$(sh_splitarray "${AARRAY_DSK_DEVICES[$_DEVICE]}" "$DSK_SIZE")"
+			TRAN_ORIGEM="$(sh_splitarray "${AARRAY_DSK_DEVICES[$_DEVICE]}" "$DSK_TRAN")"
 			sh_checkdisk "$_DEVICE"
 			sh_backup_partitions "$_DEVICE" "$NAME_ORIGEM"
 			LDISCO=$true
@@ -4549,12 +4538,12 @@ sh_confLvm() {
 	mensagem "** PVs **" "\n\n${BOLD}${WHITE}Please wait... collecting information about PVs"
 	PVs="$(pvs --noheadings)"
 	disk="${_BOOTLOADER}|\
-$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" $DSK_TRAN)|\
-$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" $DSK_SIZE)|\
-$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" $DSK_PTTYPE)|\
-$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" $DSK_MODEL)|\
-$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" $DSK_LABEL)|\
-$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" $DSK_SERIAL)"
+$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" "$DSK_TRAN")|\
+$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" "$DSK_SIZE")|\
+$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" "$DSK_PTTYPE")|\
+$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" "$DSK_MODEL")|\
+$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" "$DSK_LABEL")|\
+$(sh_splitarray "${AARRAY_DSK_DEVICES[$_BOOTLOADER]}" "$DSK_SERIAL")"
 
 	for i in "${!Amntpoint[@]}"
 	do
@@ -4855,17 +4844,17 @@ sh_clearVg() {
 	sh_umount_fs
 	last_msg="Removendo LVs (Logical Volumes)";
 	msg "INFO" "$last_msg" "$(log_info_msg "$last_msg")"
-	lvremove -ff /dev/$_vg/* 2>&1 | tee -i -a "$BOOTLOG" > "$LOGGER"
+	lvremove -ff /dev/"$_vg"/* 2>&1 | tee -i -a "$BOOTLOG" > "$LOGGER"
 	evaluate_retval "${PIPESTATUS[0]}" "$err_not_fatal"
 
 	last_msg="Removendo VG (Volume Group)";
 	msg "INFO" "$last_msg" "$(log_info_msg "$last_msg")"
-	vgremove -ff $_vg 2>&1 | tee -i -a "$BOOTLOG" > "$LOGGER"
+	vgremove -ff "$_vg" 2>&1 | tee -i -a "$BOOTLOG" > "$LOGGER"
 	evaluate_retval "${PIPESTATUS[0]}" "$err_not_fatal"
 
 	last_msg="Removendo PVs (Volumes Fisícos)";
 	msg "INFO" "$last_msg" "$(log_info_msg "$last_msg")"
-	pvremove -ff ${AConfFde[partition]} 2>&1 | tee -i -a "$BOOTLOG" > "$LOGGER"
+	pvremove -ff "${AConfFde[partition]}" 2>&1 | tee -i -a "$BOOTLOG" > "$LOGGER"
 	evaluate_retval "${PIPESTATUS[0]}" "$err_not_fatal"
 
 :<<'REM'
@@ -4879,7 +4868,7 @@ sh_clearVg() {
 	for i in "${afs[@]}"; do
 		last_msg="Removendo LV : $i";
 		msg "INFO" "$last_msg" "$(log_info_msg "$last_msg")"
-		lvremove -ff $i 2>&1 | tee -i -a "$BOOTLOG" > "$LOGGER"
+		lvremove -ff "$i" 2>&1 | tee -i -a "$BOOTLOG" > "$LOGGER"
 		evaluate_retval "${PIPESTATUS[0]}" "$err_not_fatal"
 	done
 
@@ -4975,7 +4964,7 @@ sh_chooseVg() {
 			return
 			;;
 	esac
-   if ! infoconf  " ** VG ** " "$(lvs --noheadings $vg)"\
+   if ! infoconf  " ** VG ** " "$(lvs --noheadings "$vg")"\
 						" ** VG **" "${BOLD}${RED}WARNING:${RESET} It is important to remember that removing a VG\
 is an irreversible operation and may result in data loss.\n
 Make sure you back up your data.\n
